### ISSUE TITLE
Error on metrics capture - Disk Read Bytes/sec and Per Disk Write Bytes/sec 

### ISSUE THREAD

**Issue by spicoli9000** [ManageIQ/manageiq-providers-azure#446] opened 2021-03-18 16:37 UTC
Was not able to get Azure metrics working on jansa-3 docker image. 
After debugging and finding url call and manually running, received error:
GET /subscriptions/7cde102a-5170-451c-846b-354f7b677b95/resourceGroups/myapp-rg/providers/Microsoft.Compute/virtualMachines/ansible-vm3/providers/microsoft.insights/metrics?timespan=2021-03-18T10%3A48%3A26Z%2F2021-03-18T11%3A42%3A12Z&interval=PT1M&metricnames=Percentage+CPU%2CPer+Disk+Write+Bytes%2Fsec%2CNetwork+In+Total%2CNetwork+Out+Total&aggregation=Average&api-version=2018-01-01
**Failed to find metric configuration for provider: Microsoft.Compute, resource Type: virtualMachines, metric: Per Disk Write Bytes/sec**

Valid metrics: Percentage CPU,Network In,Network Out,Disk Read Bytes,Disk Write Bytes,Disk Read Operations/Sec,Disk Write Operations/Sec,CPU Credits Remaining,CPU Credits Consumed,Data Disk Read Bytes/sec,Data Disk Write Bytes/sec,Data Disk Read Operations/Sec,Data Disk Write Operations/Sec,Data Disk Queue Depth,Data Disk Bandwidth Consumed Percentage,Data Disk IOPS Consumed Percentage,Data Disk Target Bandwidth,Data Disk Target IOPS,Data Disk Max Burst Bandwidth,Data Disk Max Burst IOPS,Data Disk Used Burst BPS Credits Percentage,Data Disk Used Burst IO Credits Percentage,OS Disk Read Bytes/sec,OS Disk Write Bytes/sec,OS Disk Read Operations/Sec,OS Disk Write Operations/Sec,OS Disk Queue Depth,OS Disk Bandwidth Consumed Percentage,OS Disk IOPS Consumed Percentage,OS Disk Target Bandwidth,OS Disk Target IOPS,OS Disk Max Burst Bandwidth,OS Disk M* Connection #1 to host management.azure.com left intact
ax Burst IOPS,OS Disk Used Burst BPS Credits Percentage,OS Disk Used Burst IO Credits Percentage,Inbound Flows,Outbound Flows,Inbound Flows Maximum Creation Rate,Outbound Flows Maximum Creation Rate,Premium Data Disk Cache Read Hit,Premium Data Disk Cache Read Miss,Premium OS Disk Cache Read Hit,Premium OS Disk Cache Read Miss,VM Cached Bandwidth Consumed Percentage,VM Cached IOPS Consumed Percentage,VM Uncached Bandwidth Consumed Percentage,VM Uncached IOPS Consumed Percentage,Network In Total,Network Out Total"}

**Ended up changing:** /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e7914f85e845/app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb
**changing both:**
Per Disk Read Bytes/sec
Per Disk Write Bytes/sec
**To:**
OS Disk Read Bytes/sec
OS Disk Write Bytes/sec

**Comment by agrare** [comment] 2021-03-18 16:40
@spicoli9000 this looks like a duplicate of https://github.com/ManageIQ/manageiq-providers-azure/issues/434 which was resolved by https://github.com/ManageIQ/manageiq-providers-azure/pull/436

**Comment by Fryguy** [comment] 2021-03-19 22:25
Duplicate of #434 

@spicoli9000 if you think this is not correct, please reopen

**Closed by Fryguy** 2021-03-19 22:25 UTC
Labels: bug
